#!/bin/bash

if [ "${1}" == "" ]; then
	echo "usage: $0 app.hex|app.elf"
	exit;
fi

sudo openocd -f interface/picoprobe.cfg -f target/rp2040.cfg -c "program ${1} verify; reset halt ; rp2040.core1 arp_reset assert 0 ; rp2040.core0 arp_reset assert 0 ; exit"
