#!/bin/bash

if [ "${1}" == "v" ]; then
	echo "usage: $0 "
	exit;
fi

sudo openocd -f interface/picoprobe.cfg -f target/rp2040.cfg -c "init ; reset halt ; rp2040.core1 arp_reset assert 0 ; rp2040.core0 arp_reset assert 0 ; exit"
